### ISSUE TITLE
CSS: cssclass datePickerPopUp's name is wrong

### ISSUE THREAD

**Issue by codehz** [edvin/tornadofx#223]
it should be renamed to `datePickerPopup`

```CSS
.date-picker-popup {
    -fx-background-color: -fx-box-border, -fx-control-inner-background;
    -fx-background-insets: 0, 1;
    /*-fx-background-radius: 0 6 6 6, 0 5 5 5;*/
    -fx-background-radius: 0;
    -fx-padding: 0;
    -fx-alignment: CENTER; /* VBox */
    -fx-spacing: 0; /* VBox */
    -fx-effect: dropshadow( three-pass-box , rgba(0,0,0,0.6) , 8, 0.0 , 0 , 0 );
}
```
