### ISSUE TITLE
[help]  Simplified  css 

### ISSUE THREAD

**Issue by QingMings** [edvin/tornadofx#281]
in css:    

        .scroll-bar:horizontal .increment-button ,
        .scroll-bar:horizontal .decrement-button {
            -fx-background-color:#EAEAEA;
            -fx-background-radius: 0em;
            -fx-padding:0 0 0 0   
        }

How to simplify it in type safe css, i try `and`  ,but not work   

        incrementButton and  decrementButton{
                         visibility=FXVisibility.HIDDEN
                         backgroundColor+=c("#EAEAEA")
                         backgroundRadius+= box(0.em)
                         padding=box(0.px)
                     }

**Comment by QingMings** [comment]
![image](https://cloud.githubusercontent.com/assets/22107668/24131849/06b5819a-0e2c-11e7-9bd6-a9074e391d4a.png)

and  

![image](https://cloud.githubusercontent.com/assets/22107668/24131864/1bdaeee8-0e2c-11e7-9762-a7e8279fb683.png)

This doesn't work

**Comment by t-boom** [comment]
You want something like
```kotlin
scrollBar and horizontal {
    s(incrementButton, decrementButton) {
        visibility = FXVisibility.HIDDEN
        backgroundColor += c("#EAEAEA")
        backgroundRadius += box(0.em)
        padding = box(0.px)
    }
}
```
which generates
```css
.scroll-bar:horizontal .increment-button, .scroll-bar:horizontal .decrement-button {
    visibility: hidden;
    -fx-background-color: rgba(234, 234, 234, 1);
    -fx-background-radius: 0em 0em 0em 0em;
    -fx-padding: 0px 0px 0px 0px;
}
```
